### ISSUE TITLE
delete vrecord v2018-12-13.tar.gz package

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/homebrew-amiaos#151]
Why do we need a copy of `vrecord v2018-12-13` here? The formula uses the regular one: 
https://github.com/amiaopensource/homebrew-amiaos/blob/cf1d4dfb9e33dc2860d9b9b99fc32632c2dd898c/vrecord.rb#L4

See also: https://github.com/amiaopensource/homebrew-amiaos/issues/121

**Comment by dericed** [comment]
resolved via commit revision

**Comment by retokromer** [comment]
Thank you!
