### ISSUE TITLE
delete `FFmpeg_4.1.1` branch

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/homebrew-amiaos#170]
Since I have been partially banned from AMIA Open Source, I cannot delete myself my branch `FFmpeg_4.1.1`. Could one possibly do it?

**Comment by kieranjol** [comment]
Partially banned? When did this happen?

**Comment by retokromer** [comment]
I don’t know. I noticed that I cannot delete here my own branch and that I cannot make anymore a release of [open-workflows](https://github.com/amiaopensource/open-workflows/releases) as I regularly did in the past.

**Comment by retokromer** [comment]
Quite funny: <img width="836" alt="amiaos" src="https://user-images.githubusercontent.com/3246607/53289053-0ed2ea80-3791-11e9-8368-144feffdeb33.png">

**Comment by retokromer** [comment]
Ping!

Could possibly one of @amiaopensource/amia-open-source-governance-team delete my `FFmpeg_4.1.1` branch, since I am not allowed anymore to do it myself?

<img width="1107" alt="Screenshot 2019-03-09 at 06 46 45" src="https://user-images.githubusercontent.com/3246607/54066829-5187ce80-4237-11e9-8061-bd7d9018b431.png">

Thank you!

**Comment by privatezero** [comment]
Hi @retokromer, I'll take care of this! Right now things are a bit of a mess regarding the permissions on this repository! We'll get some issues opened soon to try to get maintainers/contributors sorted out and make sure that people who are making releases for the various amia-os repos can get back to business as usual!
