### ISSUE TITLE
need volunteer(s) to be maintainer of this repository

### ISSUE THREAD

**Issue by dericed** [amiaopensource/homebrew-amiaos#177]
This repository needs named maintainers, ideally more than one. This repository relates closely to many other amiaopensource projects so maintenance would require coordination with other projects, particularly in updating installers at release points. More info on amiaopensource repository maintainers is under development at https://github.com/amiaopensource/governance#identification-of-maintainers.

Any volunteers? Nominations?

**Comment by retokromer** [comment]
I volunteer.

**Comment by dericed** [comment]
I second for @retokromer. Will add.

**Comment by dericed** [comment]
I added @retokromer with admin privileges. I'll leave the issue open in encouragement of a 2nd volunteer, but feel welcome to close the issue when you find it resolved. Also please document yourself as a maintainer in the readme for this repository.

**Comment by retokromer** [comment]
Thank you @dericed! More than one maintainer would be better.

**Comment by retokromer** [comment]
>Any volunteers? Nominations?

You?

**Comment by retokromer** [comment]
No many volunteers… closing.
