### ISSUE TITLE
bmdtools no rule to make target

### ISSUE THREAD

**Issue by intelligencer** [amiaopensource/homebrew-amiaos#2]
Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:

    brew install bmdtools ffmpeg libvo-aacenc xmlstarlet

Run `brew missing` for more details.
dhc2@dnb-smn-2:~$ brew install bmdtools ffmpeg libvo-aacenc xmlstarlet
==> Installing bmdtools from amiaopensource/homebrew-amiaos
==> Downloading https://github.com/lu-zero/bmdtools/archive/v0.1.zip
Already downloaded: /home/dhc2/.cache/Homebrew/bmdtools-0.1.zip
==> Patching
==> make SDK_PATH=/usr/local/include SYS=Darwin
make
SDK_PATH=/usr/local/include
SYS=Darwin

make: *** No rule to make target `/usr/local/include/DeckLinkAPIDispatch.cpp', needed by `bmdcapture'.  Stop.

**Comment by dericed** [comment]
can you try:
brew rm -f decklinksdk bmdtools vrecord
brew install vrecord

**Comment by intelligencer** [comment]
dhc2@dnb-smn-2:~$ brew rm -f decklinksdk bmdtools vrecord
Uninstalling decklinksdk...
Uninstalling vrecord...
dhc2@dnb-smn-2:~$ brew install vrecord
==> Installing vrecord from amiaopensource/homebrew-amiaos
==> Installing dependencies for vrecord: amiaopensource/amiaos/decklinksd
==> Installing vrecord dependency: amiaopensource/amiaos/decklinksdk
==> Downloading http://software.blackmagicdesign.com/SDK/Blackmagic_DeckLink_SDK
Already downloaded: /home/dhc2/.cache/Homebrew/decklinksdk-10.1.4.zip
==> Patching
/home/dhc2/.linuxbrew/Cellar/decklinksdk/10.1.4: 26 files, 588K, built in 2 seconds
==> Installing vrecord dependency: amiaopensource/amiaos/bmdtools
==> Downloading https://github.com/lu-zero/bmdtools/archive/v0.1.zip
Already downloaded: /home/dhc2/.cache/Homebrew/bmdtools-0.1.zip
==> Patching
==> make SDK_PATH=/usr/local/include SYS=Darwin
make
SDK_PATH=/usr/local/include
SYS=Darwin

make: *** No rule to make target `/usr/local/include/DeckLinkAPIDispatch.cpp', needed by `bmdcapture'.  Stop.

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/amiaopensource/homebrew-amiaos/issues

dhc2@dnb-smn-2:~$

**Comment by dericed** [comment]
ah the installer for bmdtools is expecting to be run on a Mac, the SYS=Darwin is throwing this off

**Comment by dericed** [comment]
can you try this, run `brew edit bmdtools`
then change this line
system "make", "SDK_PATH=/usr/local/include", "SYS=Darwin"
to
system "make", "SDK_PATH=/usr/local/include"
then save and rerun the previous steps

**Comment by intelligencer** [comment]
dhc2@dnb-smn-2:~$ brew edit bmdtools
Warning: Using edit because no editor was set in the environment.
This may change in the future, so we recommend setting EDITOR, VISUAL,
or HOMEBREW_EDITOR to your preferred text editor.
Error: no "edit" mailcap rules found for type "application/x-ruby"
dhc2@dnb-smn-2:~$ 

?

**Comment by dericed** [comment]
is this still an issue?

**Comment by intelligencer** [comment]
Can't say. We haven't digitized since early spring, and now its pretty much shut down.

**Comment by intelligencer** [comment]
actually, yes it is. trying to install vrecord on linux at home and ran into this exact same problem.  

localhost
/home/bleakley
::::: brew install vrecord
==> Installing vrecord from amiaopensource/homebrew-amiaos
==> Installing dependencies for amiaopensource/amiaos/vrecord: amiaopenso
==> Installing amiaopensource/amiaos/vrecord dependency: amiaopensource/a
==> Downloading http://software.blackmagicdesign.com/SDK/Blackmagic_DeckLink_SDK
Already downloaded: /home/bleakley/.cache/Homebrew/decklinksdk-10.1.4.zip
/home/bleakley/.linuxbrew/Cellar/decklinksdk/10.1.4: 26 files, 588K, built in 2 seconds
==> Installing amiaopensource/amiaos/vrecord dependency: amiaopensource/a
==> Downloading https://github.com/lu-zero/bmdtools/archive/v0.1.zip
Already downloaded: /home/bleakley/.cache/Homebrew/bmdtools-0.1.zip
==> make SDK_PATH=/usr/local/include SYS=Darwin
Last 15 lines from /home/bleakley/.cache/Homebrew/Logs/bmdtools/01.make:
2015-11-12 00:25:58 -0500

make
SDK_PATH=/usr/local/include
SYS=Darwin

make: *** No rule to make target `/usr/local/include/DeckLinkAPIDispatch.cpp', needed by `bmdcapture'.  Stop.

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/amiaopensource/homebrew-amiaos/issues

These open issues may also help:
decklinksdk, deckcontrol, and bmdtools https://github.com/Homebrew/homebrew/pull/41435

**Comment by dericed** [comment]
Does @dholm's version work for you? https://github.com/luminem/homebrew-bmdtools/blob/master/bmdtools.rb

**Comment by intelligencer** [comment]
trying. libav and ffmpeg are having a fight over symlinks.

**Comment by intelligencer** [comment]
localhost
/home/bleakley
::::: brew install --HEAD luminem/bmdtools/bmdtools
==> Installing bmdtools from luminem/homebrew-bmdtools
==> Installing dependencies for luminem/bmdtools/bmdtools: luminem/homebrew-bmdtools/libav
==> Installing luminem/bmdtools/bmdtools dependency: luminem/homebrew-bmdtools/libav
==> Cloning https://github.com/lu-zero/libav.git
Updating /home/bleakley/.cache/Homebrew/libav--git
==> Checking out branch ancillary
==> ./configure --enable-shared --disable-indev=jack --prefix=/home/bleakley/.linuxbrew/Cellar/libav/HEAD --enable-gpl --
==> make install
/home/bleakley/.linuxbrew/Cellar/libav/HEAD: 153 files, 31M, built in 2.1 minutes
==> Installing luminem/bmdtools/bmdtools
==> Cloning https://github.com/lu-zero/bmdtools.git
Updating /home/bleakley/.cache/Homebrew/bmdtools--git
==> Checking out branch ancillary
==> make SDK_PATH=/home/bleakley/.linuxbrew/include DESTDIR=/home/bleakley/.linuxbrew/Cellar/bmdtools/HEAD
Last 15 lines from /home/bleakley/.cache/Homebrew/Logs/bmdtools/01.make:
make: *** Waiting for unfinished jobs....
In file included from modes.cpp:26:0:
/home/bleakley/.linuxbrew/include/DeckLinkAPI.h:42:43: fatal error: CoreFoundation/CoreFoundation.h: No such file or directory
compilation terminated.
In file included from /home/bleakley/.linuxbrew/include/DeckLinkAPIDispatch.cpp:29:0:
/home/bleakley/.linuxbrew/include/DeckLinkAPI.h:42:43: fatal error: CoreFoundation/CoreFoundation.h: No such file or directory
compilation terminated.
In file included from modes.cpp:26:0:
/home/bleakley/.linuxbrew/include/DeckLinkAPI.h:42:43: fatal error: CoreFoundation/CoreFoundation.h: No such file or directory
compilation terminated.
make: *** [bmdcapture] Error 1
In file included from /home/bleakley/.linuxbrew/include/DeckLinkAPIDispatch.cpp:29:0:
/home/bleakley/.linuxbrew/include/DeckLinkAPI.h:42:43: fatal error: CoreFoundation/CoreFoundation.h: No such file or directory
compilation terminated.
make: *** [bmdplay] Error 1

**Comment by dericed** [comment]
many updates to the formula since this issue. Please re-test and re-open if there's still this issue.
