### ISSUE TITLE
suggestion: consider switching from sourceforge to https://github.com/osakared/qwt

### ISSUE THREAD

**Issue by ElderOrb** [amiaopensource/homebrew-amiaos#20]
Recently sourceforge seems to be working unstable so maybe makes sense to switch to github instead ?

**Comment by retokromer** [comment]
What has AMIA on SourceForge?

**Comment by ElderOrb** [comment]
qwt which is dependency for qctools

**Comment by retokromer** [comment]
Thank you! Then yes, for me it makes sense to move to GitHub.

**Comment by retokromer** [comment]
Any news on this?

**Comment by retokromer** [comment]
@ElderOrb Should we switch or should we host a copy here onto amiaos?

**Comment by retokromer** [comment]
ping

**Comment by retokromer** [comment]
@ElderOrb I guess this issue can be closed, since QCTools is no longer hosted here. If I am wrong, please feel free to reopen it.
