### ISSUE TITLE
mpv: installation

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/homebrew-amiaos#206]
At the moment, when installing our `mpv` formula, one has to uninstall ffmpeg:

<img width="810" alt="Screenshot 2019-11-01 at 14 11 01" src="https://user-images.githubusercontent.com/3246607/68026967-7393fc80-fcb1-11e9-8e51-c4e02c329d47.png">

and the formula installs the official Homebrew `ffmpeg`:

<img width="809" alt="Screenshot 2019-11-01 at 14 12 10" src="https://user-images.githubusercontent.com/3246607/68027181-f6b55280-fcb1-11e9-9544-3bbba0093ac1.png">

Yet if one wishes another `ffmpeg` installation, she or he has to uninstall ffmpeg again, and to install the wished flavour (including for the HEAD):

<img width="810" alt="Screenshot 2019-11-01 at 14 13 32" src="https://user-images.githubusercontent.com/3246607/68027122-cff71c00-fcb1-11e9-84ca-cc35d1cf61ec.png">
 
This does not give a… “nice” “user experience”.

**Comment by retokromer** [comment]
There is no problem when installing all from scratch. Closing.

**Comment by privatezero** [comment]
Thanks for the follow-up! One of the things I hate about relying on brew is the difficulties it introduces when trying to do anything custom!

**Comment by retokromer** [comment]
I actually made good experiences with Homebrew, but usually I don’t work with `keg-only` and replace Apple’s old GNU tools with their current version.
