### ISSUE TITLE
verbosity of checking for Pashua

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/homebrew-amiaos#23]
Is it really necessary to get the two messages:
```
Checking for dependency Pashua. If Pashua is not found will attempt to install
Pashua was found
```
when there was no problem at installation of `vrecord` or `audiorecorder`?

I suggest to give a success message when Pashua has been installed, respectively an error message when the installation failed, but not otherwise.

**Comment by privatezero** [comment]
Hmm, in looking over this, I think that maybe leaving it in but adding more context might be useful?  The command is designed to check to see if Pashua was installed either via homebrew or independently of homebrew- do you think adding context to the success message noting which form of pashua is installed would be useful? I personally like verbosity, but I can see how it also isn't strictly necessary!

**Comment by retokromer** [comment]
For me personally it’s indifferent (but when I was teenager we had to count every single byte ;-) I am thinking here about IT fearing archivists

**Comment by retokromer** [comment]
Oops, never use GitHub on cell…

**Comment by retokromer** [comment]
We could like to convince there archivists to embrace open source solutions and do the work inhouse when this makes sense.
