### ISSUE TITLE
undefined method `installed?' for OS::Mac::Xcode:Module

### ISSUE THREAD

**Issue by jshupeGitHub** [amiaopensource/homebrew-amiaos#237]
while attempting to install vrecord
I found a problem installing mpv

I am on linux [ ubuntu 18.04] and it seems to be a mac os error

brew install --ignore-dependencies vrecord

==> Installing vrecord from amiaopensource/amiaos
Error: An exception occurred within a child process:
RuntimeError: /home/linuxbrew/.linuxbrew/opt/mpv not present or broken
Please reinstall mpv. Sorry

brew install mpv

scenesavers@ss-43:~$ brew install mpv
Error: undefined method installed?' for OS::Mac::Xcode:Module Please report this issue: https://docs.brew.sh/Troubleshooting /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:18:in xcode_installed_version’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:10:in block in <class:XcodeRequirement>' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:60:in instance_eval’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:60:in block in satisfied?' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:191:in yielder’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:60:in satisfied?' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:456:in block in expand_requirements’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:222:in block in prune?' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:220:in catch’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:220:in prune?' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:210:in block (2 levels) in expand’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:338:in each_key' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:338:in each’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/delegate.rb:349:in block in delegating_block' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:209:in block in expand’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:208:in each' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:208:in expand’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1557:in recursive_requirements' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:450:in expand_requirements’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:388:in compute_dependencies' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:148:in verify_deps_exist’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:141:in prelude' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:328:in install_formula’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:261:in block in install' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:259:in each’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:259:in install' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in ’

brew install --ignore-dependencies vrecord

scenesavers@ss-43:~$ brew install --ignore-dependencies vrecord
Warning: --ignore-dependencies is an unsupported Homebrew developer flag!
Adjust your PATH to put any preferred versions of applications earlier in the
PATH rather than using this unsupported flag!

==> Installing vrecord from amiaopensource/amiaos
Error: An exception occurred within a child process:
RuntimeError: /home/linuxbrew/.linuxbrew/opt/mpv not present or broken
Please reinstall mpv. Sorry 

and i guess – i am stuck

**Comment by retokromer** [comment]
>Error: undefined method installed?' for OS::Mac::Xcode:Module Please report this issue: [https://docs.brew.sh/Troubleshooting](https://docs.brew.sh/Troubleshooting)

In my opinion, this is not a problem related to our formulae, but to Linuxbrew (and/or mpv). Sorry, I don’t have any possibility to delve into it during the next days, but should be able do it from the 27<sup>th</sup> of April on… if nobody steps in before.

**Comment by retokromer** [comment]
@jshupeGitHub Do you still get this error? (A lot of work has been done on both Homebrew and Linuxbrew during the last weeks.)

**Comment by jshupeGitHub** [comment]
I built 5 systems using the "formula" i 1st sorted out.
meaning I have not tried or tested the posted standard way.

I hope to have the time and materials to do such a test in the next few days

Thanks

best wishes

**Comment by retokromer** [comment]
@jshupeGitHub Do you still get this error?

**Comment by retokromer** [comment]
I presume, this is resolved. If not, feel free to reopen.
