### ISSUE TITLE
consider both Homebrew and Linuxbrew

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/homebrew-amiaos#25]
This week I had a Swiss class in which there were <sup>4</sup>/<sub>5</sub> Windows versus <sup>1</sup>/<sub>5</sub> macOS computers. I personally think we should systematically try to make our software easily available not only via Homebrew but also via Linuxbrew, which usually requires only a little additional work. This way people using Linux or the Windows Subsystem for Linux (Ubuntu) can easily install, use and update it.

I also know that in the ASEAN countries macOS is almost inexistent.

**Comment by privatezero** [comment]
I agree!  I am hoping to figure out some better alternatives to Pashua, which is one thing that I know ties some of our tools to macOS.  Is there a good resource that summarizes some of the things to do to make scripts more cross-platform/traps to avoid when writing for both Linux and macOS?

**Comment by retokromer** [comment]
Not that I know, but I could try to distill a checklist from my experiences.

**Comment by privatezero** [comment]
That would be amazing!  I know there is a difference in how the `date` command functions, and I seem to recall `open` being limited to mac, but other than that I haven't been to sure of what to avoid!

**Comment by retokromer** [comment]
On Windows it’s not working 100% as a pure Ubuntu installation, but it’s getting more and more close.

**Comment by retokromer** [comment]
I updated the [CONTRIBUTING.md](https://github.com/amiaopensource/homebrew-amiaos/commit/4864079a3f0c49b191874060f9b92dd0bda71717) page, recommending to programme portable code.
