### ISSUE TITLE
Error on install vrecord

### ISSUE THREAD

**Issue by jf-blanco** [amiaopensource/homebrew-amiaos#274]
When I try to install vrecord on macos Catalina 10.15.7 (not xcode installed).
I get this error:

Last 15 lines from /Users/Karissa/Library/Logs/Homebrew/gtkdialog/01.configure:
checking whether yytext is a pointer... yes
checking for bison... bison -y
checking for pkg-config... /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GTK... no
configure: error: Package requirements (gtk+-2.0 >= 2.0.0) were not met:

Package 'xcb-shm', required by 'cairo', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GTK_CFLAGS
and GTK_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

GTK 2.24.33 seems to be installed. How do I adjust the PKG_CONFIG_PATH or set the GTK_CFLAGS
and GTK_LIBS
Complete noob in these matters out here.

**Comment by EG-tech** [comment]
I was seeing this same error in Mojave yesterday but I believe @dericed solved it with #275 - if you can @jf-blanco, try just running `brew install vrecord` again?

see also https://github.com/amiaopensource/vrecord/issues/665

**Comment by retokromer** [comment]
Possibly, you need to run
```
brew update && brew upgrade
```
in order to have “everything” updated.

**Comment by jf-blanco** [comment]
Problem solved. vrecord up and running. Ready to rock and test capture cards via intensity shuttle and ultrastudio 4k
