### ISSUE TITLE
Cable Bible Tool not installing

### ISSUE THREAD

**Issue by nkrabben** [amiaopensource/homebrew-amiaos#278]
After I `brew install cable-bible`, I try to run it `cable-bible`. I then receive an error.
```
LSCopyApplicationURLsForBundleIdentifier() failed while trying to determine the application with bundle identifier 193-    },.
```

Searching hasn't yielded anything that helps me understand what the issue is.

**Comment by retokromer** [comment]
On which operating system are you?

**Comment by nkrabben** [comment]
macOS 10.15

**Comment by retokromer** [comment]
Thank you! I have not access to this now at home, but tomorrow at the lab.

**Comment by retokromer** [comment]
@nkrabben I’ve not forgotten this one, but still trying to reproduce. The error message you got remains mysterious to me.

**Comment by retokromer** [comment]
@nkrabben The error is related to the Cable Bible [script](https://github.com/amiaopensource/cable-bible/blob/master/cable-bible), not to this formula.

I did open an [issue](https://github.com/amiaopensource/cable-bible/issues/50) there. Thank you for reporting!
