### ISSUE TITLE
Error compiling gtkdialog

### ISSUE THREAD

**Issue by alexhabgood** [amiaopensource/homebrew-amiaos#282]
Trying to install gtkdialog on ubuntu 18.04, but I'm getting the following error:

> maceadmin@amacewrk05:~$ brew install gtkdialog
> ==> Installing gtkdialog from amiaopensource/amiaos
> ==> Downloading https://storage.googleapis.com/google-code-archive-downloads/v2/
> ######################################################################## 100.0%
> ==> ./configure
> ==> make
> Last 15 lines from /home/maceadmin/.cache/Homebrew/Logs/gtkdialog/02.make:
> /home/linuxbrew/.linuxbrew/bin/ld: widget_window.o:(.bss+0x28): multiple definition of `project_space_fill'; gtkdialog.o:(.bss+0xb0): first defined here
> /home/linuxbrew/.linuxbrew/bin/ld: widget_window.o:(.bss+0x2c): multiple definition of `project_space_expand'; gtkdialog.o:(.bss+0xb4): first defined here
> /home/linuxbrew/.linuxbrew/bin/ld: widget_window.o:(.bss+0x30): multiple definition of `function_signals_block'; gtkdialog.o:(.bss+0xb8): first defined here
> collect2: error: ld returned 1 exit status
> Makefile:342: recipe for target 'gtkdialog' failed
> make[3]: *** [gtkdialog] Error 1
> make[3]: Leaving directory '/tmp/gtkdialog-20210421-20747-9gd6v5/gtkdialog-0.8.3/src'
> Makefile:265: recipe for target 'all' failed
> make[2]: *** [all] Error 2
> make[2]: Leaving directory '/tmp/gtkdialog-20210421-20747-9gd6v5/gtkdialog-0.8.3/src'
> Makefile:321: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/tmp/gtkdialog-20210421-20747-9gd6v5/gtkdialog-0.8.3'
> Makefile:257: recipe for target 'all' failed
> make: *** [all] Error 2

Thanks in advance.

**Comment by privatezero** [comment]
Hi @alexhabgood, this should be related to an issue that cropped up a little while back - we are most of the way there with a fix for this at https://github.com/amiaopensource/homebrew-amiaos/pull/277, but that PR just needs to be finalized to not cause issues on the Mac side. Should be resolved soon!

**Comment by alexhabgood** [comment]
Thanks for confirming @privatezero. I've compiled gtkdialog-0.8.4c manually and it seems to be working fine. Will switch back to the proper homebrew version once the PR is resolved.
