### ISSUE TITLE
make fails compiling ffmpegdecklink

### ISSUE THREAD

**Issue by lucatze** [amiaopensource/homebrew-amiaos#284]
```
➜  ~ brew doctor
Your system is ready to brew.
```

```
➜  ~ brew config
HOMEBREW_VERSION: 3.1.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: d89eda09abbeae907eb88bd6d01dc9cde7ff0e19
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5571ad2bec4ef62ba3b28b51528bcd74899a31d3
Core tap last commit: 69 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit ivybridge
Clang: 12.0 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.5
```

```
➜  ~ brew install amiaopensource/amiaos/ffmpegdecklink
==> Installing ffmpegdecklink from amiaopensource/amiaos
==> Downloading https://ffmpeg.org/releases/ffmpeg-4.4.tar.xz
Already downloaded: /Users/luke/Library/Caches/Homebrew/downloads/837c094bbbd62f9664825da5b8206acd9a27ed63510f91410034a4a1572d3750--ffmpeg-4.4.tar.xz
==> ./configure --prefix=/usr/local/Cellar/ffmpegdecklink/4.4 --disable-shared --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-gpl --ena
==> make
Last 15 lines from /Users/luke/Library/Logs/Homebrew/ffmpegdecklink/02.make:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/atomic:1847:21: error: unknown type name 'ptrdiff_t'
    _Tp* operator-=(ptrdiff_t __op) volatile _NOEXCEPT {return fetch_sub(__op) - __op;}
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/atomic:1849:21: error: unknown type name 'ptrdiff_t'
    _Tp* operator-=(ptrdiff_t __op) _NOEXCEPT          {return fetch_sub(__op) - __op;}
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/atomic:2182:46: error: unknown type name 'ptrdiff_t'
atomic_fetch_add(volatile atomic<_Tp*>* __o, ptrdiff_t __op) _NOEXCEPT
                                             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
3 errors generated.
make: *** [libavdevice/decklink_common.o] Error 1
make: *** Waiting for unfinished jobs....
20 errors generated.
make: *** [libavdevice/decklink_dec.o] Error 1
```

**Comment by skullflowerss** [comment]
I have the same problem. 

I tried to uninstall vrecord, ffmpeg. Do the linux command to force the instalation and nothing is working.

I have macOS: 11.2.3-x86_64 and Xcode 12.5

**Comment by dericed** [comment]
Hi @lucatze @skullflowerss, for a workaround you can run `brew install ffmpegdecklink --HEAD`. I think this issue is related to needing some of the updates from https://github.com/FFmpeg/FFmpeg/commit/d422b2ed87ee7d3b3014cd3fac553e6aad7d4f14.patch and related patches. I'm hoping to find the right patch history to add to the installer until the next release.

**Comment by retokromer** [comment]
@lucatze Please test again on your end.

**Comment by lucatze** [comment]
> @lucatze Please test again on your end.

I'M not sure if i did everything right concerning the version (did it just reinstall HEAD?)

`brew reinstall ffmpegdecklink
==> Cloning https://github.com/FFmpeg/FFmpeg.git
Updating /Users/luke/Library/Caches/Homebrew/ffmpegdecklink--git
From https://github.com/FFmpeg/FFmpeg
   553619eacb..071930de72  master     -> origin/master
==> Checking out branch master
Already on 'master'
Your branch is behind 'origin/master' by 208 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 071930de72 avformat/mov: add option to use tfdt for fragment timestamps.
==> Reinstalling amiaopensource/amiaos/ffmpegdecklink 
==> ./configure --prefix=/usr/local/Cellar/ffmpegdecklink/HEAD-071930d_1 --disable-shared --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enabl
==> make
==> Caveats
ffmpegdecklink is keg-only, which means it was not symlinked into /usr/local,
because anything that needs this will know where to look.

If you need to have ffmpegdecklink first in your PATH, run:
  echo 'export PATH="/usr/local/opt/ffmpegdecklink/bin:$PATH"' >> ~/.zshrc

==> Summary
🍺  /usr/local/Cellar/ffmpegdecklink/HEAD-071930d_1: 12 files, 57.2MB, built in 6 minutes 24 seconds
`

**Comment by retokromer** [comment]
Thank you, @lucatze, for testing. It should now work fine for you too.
