### ISSUE TITLE
Error with brew install vrecord (Ubuntu 18.04)

### ISSUE THREAD

**Issue by jfeakes** [amiaopensource/homebrew-amiaos#326]
After following all previous steps of Linux install guide on github page on a BitCurator image (bionic 18.04) Getting the following error:
```
Last 15 lines from /home/bitcurator/.cache/Homebrew/Logs/gtkdialog/02.make:
else \
  rc=$?; \
  CDPATH="${ZSH_VERSION+.}:" && cd . && \
  $restore $backupdir/* `echo "./gtkdialog.info" | sed 's|[^/]*$||'`; \
fi; \
rm -rf $backupdir; exit $rc
/bin/bash: line 9: makeinfo: command not found
Makefile:338: recipe for target 'gtkdialog.info' failed
make[2]: *** [gtkdialog.info] Error 127
make[2]: Leaving directory '/tmp/gtkdialog-20220607-22530-9bc217/gtkdialog-0.8.4d/doc'
Makefile:424: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/gtkdialog-20220607-22530-9bc217/gtkdialog-0.8.4d'
Makefile:363: recipe for target 'all' failed
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
 https://github.com/amiaopensource/homebrew-amiaos/issues
```
Any help appreciated!

**Comment by privatezero** [comment]
Thanks for reporting @jfeakes - this looks to be related to the issue reported in: https://github.com/amiaopensource/vrecord/issues/696.

In that case the problem was solved by reinstalling `texinfo` - could you try that (command should be `sudo apt reinstall texinfo`) and let us know if it helps with the issue?

**Comment by jfeakes** [comment]
> In that case the problem was solved by reinstalling `texinfo` - could you try that (command should be `sudo apt reinstall texinfo`) and let us know if it helps with the issue?

Thanks for the reply.
Running `sudo apt-get install --reinstall texinfo` and `brew install gtkdialog` appears to have resolved the issue and `brew install vrecord` completed successfully.

**Comment by retokromer** [comment]
@privatezero Should this information be added on the [Steps for a successful install of Vrecord on Linux](https://github.com/amiaopensource/vrecord/blob/main/Resources/Documentation/linux_installation.md) page? I opened here https://github.com/amiaopensource/homebrew-amiaos/pull/327.

**Comment by retokromer** [comment]
closing, see https://github.com/amiaopensource/homebrew-amiaos/pull/327
