### ISSUE TITLE
DV stream break produces "dts to muxer" errors

### ISSUE THREAD

**Issue by photonclock** [amiaopensource/homebrew-amiaos#365]
I'm capturing DV tapes from old DV camcorders. ffmpeg-dl on macOS 12.6.8

Command used:
ffmpeg-dl -f avfoundation -capture_raw_data true -i "PV-DV53" -c copy -map 0 -f rawvideo filename.dv

Works great until there's a break in the video stream (a gap of unrecorded time on the tape). When the stream re-starts, ffmpeg-dl begins writing out hundreds of these error messages:

[avfoundation @ 0x7fa358f05180] DTS 0 < 46746700 out of orderitrate=28745.1kbits/s speed=   1x    
[rawvideo @ 0x7fa35a50b0c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 1400 >= -1
[rawvideo @ 0x7fa35a50b0c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 1400 >= 0
[rawvideo @ 0x7fa35a50b0c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 1400 >= 1
[rawvideo @ 0x7fa35a50b0c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 1400 >= 2
[rawvideo @ 0x7fa35a50b0c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 1400 >= 3
[rawvideo @ 0x7fa35a50b0c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 1400 >= 4

I was told that ffmpeg-dl was really good at capturing DV tapes start to end regardless of timecode breaks or glitches or breaks in the stream. Is there way to avoid these errors with an alternate capture command?

**Comment by retokromer** [comment]
@photonclock Thank you for reporting. It seems to me that this is related to the software, not the installation formula.

**Comment by dericed** [comment]
I suggest either moving this issue upstream to https://trac.ffmpeg.org/ or swapping to using the [dvrescue CLI](https://mediaarea.net/DVRescue) with `dvrescue -m filename.dv`.
