### ISSUE TITLE
delete `require "formula"`

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/homebrew-amiaos#39]
If I’m not completely wrong, since some time now the `require "formula"` statement in the beginning is not longer needed. Should I remove it from the ones that still have it? The current situation is:

- [ ] audiorecorder.rb
- [x] bmdtools.rb
- [x] deckcontrol.rb
- [x] decklinksdk.rb
- [ ] digibase.rb
- [x] ffmprovisr.rb
- [ ] ltopers.rb
- [ ] mkvparse.rb
- [ ] pbprotracktor.rb
- [x] qcli.rb
- [x] qctools.rb
- [x] qwt-qt5.rb
- [ ] vrecord.rb

Id est six formulae to be modified and seven already fine.

**Comment by privatezero** [comment]
That makes sense to me! I just tested the audiorecorder formula with `brew audit` and can confirm that homebrew doesn't complain about a lack of `require formula`.

**Comment by retokromer** [comment]
Thank you, @privatezero! I opened a PR, but only on three formulae, because I did a some mistake and merged directly three formulae…

I don’t think there is any need to add a `revision` here, as nothing on the behaviour has been modified.

**Comment by retokromer** [comment]
Resolved by https://github.com/amiaopensource/homebrew-amiaos/pull/40.
