### ISSUE TITLE
bmdtools causing fail on reinstall

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/homebrew-amiaos#4]
Hi!  I did a brew update/upgrade that caused vrecord to fail in the same way as it did for Libby in issue 33.  [ https://github.com/amiaopensource/vrecord/issues/33](url).

I tried a clean install after uninstalling ffmpeg,libav,bmdtools and vrecord and now am unable to reinstall vrecord unless I force it to ignore dependencies (in which case it of course does not work).  Seems that bmdtools is having install issues.

> D-172-25-104-167:~ media$ brew upgrade
==> Upgrading 1 outdated package, with result:
amiaopensource/amiaos/vrecord 0.7.11
==> Upgrading amiaopensource/amiaos/vrecord
==> Installing dependencies for amiaopensource/amiaos/vrecord: amiaopensource/amiaos/bmdtools
==> Installing amiaopensource/amiaos/vrecord dependency: amiaopensource/amiaos/bmdtools
==> Downloading https://github.com/lu-zero/bmdtools/archive/v0.1.zip
==> Downloading from https://codeload.github.com/lu-zero/bmdtools/zip/v0.1
######################################################################## 100.0%
==> make SDK_PATH=/usr/local/include SYS=Darwin
Last 15 lines from /Users/media/Library/Logs/Homebrew/bmdtools/01.make:
    av_free_packet(&pkt);
    ^
/usr/local/Cellar/ffmpeg/3.0/include/libavcodec/avcodec.h:4040:6: note: 'av_free_packet' has been explicitly marked deprecated here
void av_free_packet(AVPacket *pkt);
     ^
bmdplay.cpp:789:5: warning: 'av_free_packet' is deprecated [-Wdeprecated-declarations]
    av_free_packet(&pkt);
    ^
/usr/local/Cellar/ffmpeg/3.0/include/libavcodec/avcodec.h:4040:6: note: 'av_free_packet' has been explicitly marked deprecated here
void av_free_packet(AVPacket *pkt);
     ^
15 warnings and 5 errors generated.
make: *** [bmdcapture] Error 1
make: *** Waiting for unfinished jobs....
make: *** [bmdplay] Error 1

I also tried reinstalling Decklink SDK 10.1.4, which was giving me a checksum mismatch error when using the amiaopensource tap.  I was able to reinstall it by downloading it from blackmagic and manually placing it where homebrew could find it.   This problem has been recreated across three computers running osx- always triggered by brew update/upgrade.

**Comment by dericed** [comment]
can you try `brew reinstall bmdtools`

**Comment by dericed** [comment]
It seems like Blackmagic has pulled down the public url of their SDK which used to be at http://software.blackmagicdesign.com/SDK/Blackmagic_DeckLink_SDK_10.1.4.zip. I asked them about it at https://twitter.com/dericed/status/702568793860657152.  Perhaps there is another url?

**Comment by dericed** [comment]
I found a mirror to the decklink sdk and added it here: https://github.com/amiaopensource/homebrew-amiaos/commit/36c218d0af33f7c8bee46ff18e884ab4d1738d52. @privatezero can you try to `brew update` and reinstall again.

**Comment by privatezero** [comment]
Thanks for looking into this!  Now getting the error

> media$ brew install amiaopensource/amiaos/bmdtools
==> Installing bmdtools from amiaopensource/amiaos
Error: undefined method `rev' for #<Class:0x007f9cac4ca6f8>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/amiaopensource/homebrew-amiaos/decklinksdk.rb:8:in `<class:Decklinksdk>'
/usr/local/Library/Taps/amiaopensource/homebrew-amiaos/decklinksdk.rb:3:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in `klass'
/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:169:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:209:in `factory'
/usr/local/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Library/Homebrew/dependency.rb:93:in `block in expand'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependency.rb:80:in `expand'
/usr/local/Library/Homebrew/formula.rb:1222:in `recursive_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:129:in `verify_deps_exist'
/usr/local/Library/Homebrew/formula_installer.rb:122:in `prelude'
/usr/local/Library/Homebrew/cmd/install.rb:214:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Library/brew.rb:83:in `<main>'

**Comment by dericed** [comment]
`rev` should have been `revision`. Typo fixed, please retry.

**Comment by privatezero** [comment]
Still getting what looks like same error

> D-172-25-104-167:~ media$ brew reinstall amiaopensource/amiaos/bmdtools
==> Reinstalling amiaopensource/amiaos/bmdtools
==> Downloading https://github.com/lu-zero/bmdtools/archive/v0.1.zip
==> Downloading from https://codeload.github.com/lu-zero/bmdtools/zip/v0.1
######################################################################## 100.0%
==> make SDK_PATH=/usr/local/include SYS=Darwin
Last 15 lines from /Users/media/Library/Logs/Homebrew/bmdtools/01.make:
    av_free_packet(&pkt);
    ^
/usr/local/Cellar/ffmpeg/3.0/include/libavcodec/avcodec.h:4040:6: note: 'av_free_packet' has been explicitly marked deprecated here
void av_free_packet(AVPacket *pkt);
     ^
bmdplay.cpp:789:5: warning: 'av_free_packet' is deprecated [-Wdeprecated-declarations]
    av_free_packet(&pkt);
    ^
/usr/local/Cellar/ffmpeg/3.0/include/libavcodec/avcodec.h:4040:6: note: 'av_free_packet' has been explicitly marked deprecated here
void av_free_packet(AVPacket *pkt);
     ^
15 warnings and 5 errors generated.
make: *** [bmdcapture] Error 1
make: *** Waiting for unfinished jobs....
make: *** [bmdplay] Error 1

**Comment by dericed** [comment]
I think bmdtools may not build with ffmpeg 3 as it is using /usr/local/Cellar/ffmpeg/3.0/include/libavcodec/avcodec.h.
Can you try:
`brew switch ffmpeg 2.8.6`?

**Comment by privatezero** [comment]
Well, good news and bad news- switching to ffmpeg 2.8.6 allows me to reinstall bdmtools so that appears to have been the issue.

Looks like a link is off now for installing vrecord through brew

> brew install vrecord
==> Installing vrecord from amiaopensource/amiaos
==> Downloading https://github.com/amiaopensource/vrecord/archive/v0.7.11.zip
==> Downloading from https://codeload.github.com/amiaopensource/vrecord/zip/v0.7.11

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "vrecord"
Download failed: https://codeload.github.com/amiaopensource/vrecord/zip/v0.7.11

I was able to manually install it by copying it off one of my computers that hasn't been upgraded.  Now I get the original error that started after update when trying to run vrecord (which caused me to attempt the clean install)

> media$ vrecord -p
dyld: Library not loaded: /System/Library/Frameworks/Jackmp.framework/Versions/A/Jackmp
  Referenced from: /usr/local/opt/ffmpeg/lib/libavcodec.56.dylib
  Reason: image not found
dyld: Library not loaded: /System/Library/Frameworks/Jackmp.framework/Versions/A/Jackmp
  Referenced from: /usr/local/bin/ffplay
  Reason: image not found
/usr/local/bin/vrecord: line 557: 68084 Trace/BPT trap: 5       bmdcapture -m ${standard} -V "${video_input}" -A "${audio_input}" -c 8 -s 32 -p "${video_bitdepth}" -F nut -f pipe:1
     68085                       | ffplay -v info -hide_banner -stats -i - -window_title "mode:${runtype} - video:'${video_input_choice}' audio:'${audio_input_choice}'" -vf "${playbackfilter}"

**Comment by dericed** [comment]
I named the release `0.7.11.zip` instead `v0.7.11.zip`. Another typo. Fixed and please retry.

**Comment by privatezero** [comment]
Install now works through brew, but have same error as above when trying to run vrecord.  I will try to take a look at some of our computers that haven't been upgraded yet to see if I can isolate what is causing it. (They have deep freeze, so I am able to mess them up and then revert)  Thank you so much for helping!

> media$ vrecord -p
Which playback view?
1) Visual
2) Visual + Numerical
Select a playback view: 1
dyld: Library not loaded: /System/Library/Frameworks/Jackmp.framework/Versions/A/Jackmp
  Referenced from: /usr/local/opt/ffmpeg/lib/libavcodec.56.dylib
  Reason: image not found
dyld: Library not loaded: /System/Library/Frameworks/Jackmp.framework/Versions/A/Jackmp
  Referenced from: /usr/local/bin/ffplay
  Reason: image not found
/usr/local/bin/vrecord: line 800: 80159 Trace/BPT trap: 5       bmdcapture -m ${standard} -V "${video_input}" -A "${audio_input}" -c 8 -s 32 -p "${video_bitdepth}" -F nut -f pipe:1
     80160                       | ffplay -v info -hide_banner -stats -i - -window_title "mode:${runtype} - video:'${video_input_choice}' audio:'${audio_input_choice}'" -vf "${playbackfilter}"

**Comment by dericed** [comment]
Not sure what Jackmp is. You may need a reinstall of ffmpeg or to check `brew doctor` for clues.

**Comment by dericed** [comment]
@privatezero after the changes the update worked for me. Lemme know if you're stuck at this point.

**Comment by privatezero** [comment]
Hmm, well glad to know it isn't a universal problem! (Although I was hoping this was a problem on the FFMPEG side and would get fixed by them in an update). Thanks for all the help so far!  I am still stuck in a bit of a vicious cycle here.  

Tried erasing and reinstalling Homebrew and retapping/reinstalling vrecord and dericed/mm
> D-172-25-104-167:local media$ brew doctor
Your system is ready to brew.

Get this error when using FFMPEG 3.0

> media$ vrecord -p
Which playback view?
1) Visual
2) Visual + Numerical
Select a playback view: 1
dyld: Library not loaded: /usr/local/opt/ffmpeg/lib/libavcodec.56.dylib
  Referenced from: /usr/local/bin/bmdcapture
  Reason: image not found

Which is exactly the same problem that happened in issue 33.  When I attempt the fix that worked for that (deleting ffmpeg, libav, bmdtools and vrecord then using brew install vrecord) it will error until I switch to FFMPEG 2.8.6.  If I attempt to run vrecord using 2.8.6 then I get the messages above with the jackmp.  Upon switching back to the newly installed FFMPEG 3.0 I get the 

> dyld: Library not loaded: /usr/local/opt/ffmpeg/lib/libavcodec.56.dylib

Rinse and repeat!!

When I mess around on my locked public computers that haven't been updated for a while, upgrading dericed/mm (which includes FFMPEG) causes things to break, but then switching back to FFMPEG version 2.8.1_1 makes it work again, so I think the issue is with FFMPEG libraries getting lost in the shuffle somehow...

**Comment by dericed** [comment]
That tap was migrated to an organizational account. Run:
```
brew untap dericed/mm
brew tap mediamicroservices/mm
```
I also updated the formula based on advice in a never-finished pull request https://github.com/Homebrew/homebrew/pull/41435, so `brew update && brew upgrade`.

**Comment by privatezero** [comment]
Woohoo! We are cooking with gas now!  I tapped the new mm, wiped all versions of FFMPEG and then used a different method to reinstall FFMPEG 2.8.6 than I tried yesterday (I took the old homebrew install script and copied it over to my github and tapped that).  Thank you so much for taking the time to help!  Are you still running FFMPEG 2.8.6 while using vrecord, or are you able to use it with 3.0?

**Comment by dericed** [comment]
i think ffmpeg 3.0 is ok, let me know if you find otherwise.

**Comment by privatezero** [comment]
Still haven't been able to use it with ffmpeg 3.0.  The issue appears to be that since  I need to use 2.8.6 to get bmdtools to build it is looking for outdated libraries when I switch to 3.0?

> dyld: Library not loaded: /usr/local/opt/ffmpeg/lib/libavcodec.56.dylib

This has changed to libavcodec.57.dylib with the update to 3.0.  Both 2.8.6 and 2.8.1_1 look like they use libavcodec.56.dylib, so I was able to get this build of bmdtools to work with them.  Going back to 2.8 or forward to 3.0 causes the issues.

I went into bmdcapture using hexfiend and changed all the libraries that it was telling me it couldn't find to the new ones one by one-
libavcodec.56.dylib -> libavcodec.57.dylib
libavformat.56.dylib -> libavformat.57.dylib
libswscale3.dylib -> libswscale4.dylib
libavutil.54.dylib -> libavutil.55.dylib

and then it will at least start for a second before freaking out with a codec error (obviously there is more that needs to be changed beyond these libraries).

> Select a playback view: 1
[NULL @ 0x7fcecc800600] [IMGUTILS @ 0x7fff5cc72800] Picture size 0x74 is invalid
[NULL @ 0x7fcecc800600] Ignoring invalid width/height values
[NULL @ 0x7fcecc800600] [IMGUTILS @ 0x7fff5cc72800] Picture size 0x0 is invalid
[v210 @ 0x7fcecc800600] Specified pixel format -1 is invalid or not supported
could not open codec

I tried this on our lab computers and my personal laptop as well, and was having the same issue of not being able to build bmdtools using 3.0 and then it not being able to find the new libraries after building it with 2.8.6.  The common thread across those computers is of course me- I wonder if anyone else is having problems with a clean install?

**Comment by dericed** [comment]
i think you'd need `brew reinstall bmdtools` after an ffmpeg switch. Perhaps there's a way to adjust the ffmpeg dependency in the bmdtools formula to accommodate this.

**Comment by privatezero** [comment]
Made no changes on this end (short of making sure packages are current), but today I was able to get bmdtools to install with FFMPEG 3.0, so it looks like whatever issue bmdtools was having , it has resolved itself!

**Comment by dericed** [comment]
bmdtools needs some api changes at https://github.com/lu-zero/bmdtools/commit/21557ab71e82cac39d84212e8544c62063c58ddd that are after the last release. I made a fork to made new release of bmdtools (at least via a fork) at https://github.com/amiaopensource/bmdtools/releases for now. If you're still having trouble try:
```
brew update
brew reinstall bmdtools
brew install vrecord
```
