### ISSUE TITLE
qwt-qt5 install problem

### ISSUE THREAD

**Issue by brnco** [amiaopensource/homebrew-amiaos#51]
Hey, just wanted to document a problem/ solution I had while installing QCTools via Homebrew. I was getting the following error on the qwt-qt5 install, a QCTools dependency:

`spc13-s6al:~ bcoates$ brew install amiaopensource/amiaos/qwt-qt5
==> Installing qwt-qt5 from amiaopensource/amiaos
==> Downloading https://downloads.sourceforge.net/project/qwt/qwt/6.1.3/qwt-6.1.
Already downloaded: /Users/bcoates/Library/Caches/Homebrew/qwt-qt5-6.1.3.tar.bz2
==> Patching
patching file designer/designer.pro
Hunk #1 succeeded at 115 (offset -11 lines).
==> /usr/local/opt/qt/bin/qmake -config release -spec macx-clang
Last 15 lines from /Users/bcoates/Library/Logs/Homebrew/qwt-qt5/01.qmake:
2017-06-28 16:05:32 -0700

/usr/local/opt/qt/bin/qmake
-config
release
-spec
macx-clang

Project ERROR: Could not resolve SDK Path for 'macosx'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/amiaopensource/homebrew-amiaos/issues

These open issues may also help:
qwt-qt5: compilation errors with Qt 5.8 https://github.com/amiaopensource/homebrew-amiaos/issues/19`

Indeed, the above-mentioned issue #19 did help, inasmuch as I was led here:
https://github.com/therecipe/qt/issues/327

The solution was to download XCode, start it, then do:
Preferences -> Locations -> Command Line Tools -> select SDK

I'm still on 10.11.6, El Capitan, this install is on a work computer managed by an IT department, so I couldn't download the latest version of XCode, but previous versions can be gotten here (with an Apple ID), 7.3.1 worked for me:
https://developer.apple.com/xcode/downloads/

Anyway, hope that saves somebody else a couple hours.

**Comment by ablwr** [comment]
Oh, I ran into a similar problem too! Thanks for documenting how to fix it. I wasn't clever enough to come up with a viable solution -- I tried so many things, so when it started working, I was just like "YAAAAYAYAYAYYAYAYAYA" and lit several books on fire and ran around the house and then went back to whatever I was doing. You the best!

**Comment by retokromer** [comment]
As said in https://github.com/amiaopensource/homebrew-amiaos/issues/19#issuecomment-305756657, the current version 5.9 works fine on my side. And this, also on 10.11.6.

**Comment by retokromer** [comment]
Added a [note](https://github.com/amiaopensource/homebrew-amiaos/commit/d9d98d7de28d5333edf24c7a374cb8cdcd720d3f) to the ReadMe file.
