### ISSUE TITLE
move unmaintained formulae to abandoned projects

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/homebrew-amiaos#83]
If I’m not missing something, then the two following formulae are not longer used:
- bmdtools
- deckcontrol

Therefore, I suggest to move them to the [Abandoned project](https://github.com/amiaopensource/homebrew-amiaos#abandoned-project) section for user’s clarity. If there is a consensus, I’ll add this to the [PR](https://github.com/amiaopensource/homebrew-amiaos/pull/82).

cc @dericed

**Comment by dericed** [comment]
I listed myself as maintainer of the deckcontrol repo. bmdtools isn't very active, but IMHO it's useful. Might be worth asking lu-zero but I suspect he'd consider the project actively maintained.

**Comment by retokromer** [comment]
Yes, `deckcontrol` is useful. I did not understand which formula does need it and I have seen only now in the formula that it’s related BAVC. Sorry for the noise.

I’ll check with Luca regarding `bmdtools`.
