### ISSUE TITLE
Error when installing qctools via homebrew (OSC X 10.8.5)

### ISSUE THREAD

**Issue by iamdamosuzuki** [amiaopensource/homebrew-amiaos#9]
From some Googling it appears the error is with qt5. Not sure though

> Last 15 lines from /Users/mini03/Library/Logs/Homebrew/qwt-qt5/02.make:
> /usr/local/Cellar/qt5/5.6.1-1/lib/QtCore.framework/Headers/qstring.h:1325:53: error: no type named 'u32string' in namespace 'std'
> inline QString QString::fromStdU32String(const std::u32string &s)
>                                                ~~~~~^
> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> 20 errors generated.
> make[1]: **\* [obj/qwt_color_map.o] Error 1
> make[1]: **\* Waiting for unfinished jobs....
> 20 errors generated.
> make[1]: **\* [obj/qwt_clipper.o] Error 1
> 20 errors generated.
> 20 errors generated.
> make[1]: **\* [obj/qwt_column_symbol.o] Error 1
> make[1]: **\* [obj/qwt_abstract_scale_draw.o] Error 1
> make: **\* [sub-src-make_first-ordered] Error 2

**Comment by utzig** [comment]
`u32string` is part of C++11. Not sure if your Xcode is too old (without c++11) or maybe c++11 is not being enabled somehow. You probably didn't build qt5 yourself because Homebrew already has it in binary form but doesn't look like a problem with qt5 itself.

**Comment by dericed** [comment]
@iamdamosuzuki can we close this issue? Any suggestions for documentation?

**Comment by retokromer** [comment]
@dericed Installing QCTools via Linuxbrew gives an error: "Xcode path is not set." I don't know if Xcode is really needed, I guess a standard compiler on Linux would fit.

**Comment by retokromer** [comment]
@dericed +1 for closing this issue.

**Comment by dericed** [comment]
Closing. @iamdamosuzuki feel welcome to reopen if there's a need
